
package arraylist;

public class App 
{
   public static void main( String args[] )
   {
      System.out.println("Testing ArrayList");
      ArrayList list = new ArrayList(); 
      
      list.insertAtFront( -1 );
      list.print();
      list.insertAtFront( 0 );
      list.print();
      list.insertAtBack( 1 );
      list.print();
      list.insertAtBack( 5 );
      list.print();
      list.insertAtFront( 9 );
      list.print();
      list.insertAtFront( 8 );
      list.print();
      list.insertAtBack( 7 );
      list.print();
      list.insertAtBack( 6 );
      list.print();
      list.insertAtFront( -1 );
      list.print();
      list.insertAtFront( 4 );
      list.print();
      list.insertAtBack( 10 );
      list.print();
      list.insertAtBack( 20 );
      list.print();
      Object removedObject = list.removeFromFront();
      list.print();
      removedObject = list.removeFromBack();
      list.print();
      list.makeEmpty();
      list.print();
      
      System.out.println("Testing ArrayQueue");
      ArrayQueue queue = new ArrayQueue();
      queue.enqueue( 1 );
      queue.print();
      queue.enqueue( 2 );
      queue.print();
      queue.enqueue( 3 );
      queue.print();
      queue.enqueue( 4 );
      queue.print();
      System.out.println(queue.length());
      removedObject = queue.dequeue();
      queue.print();
      System.out.println(queue.length());
      removedObject = queue.dequeue();
      queue.print();
      System.out.println(queue.length());
      removedObject = queue.dequeue();
      queue.print();
      System.out.println(queue.length());
      removedObject = queue.dequeue();
      queue.print();
      queue.printDebugger();
      queue.enqueue( 16 );
      queue.print();
      queue.enqueue( 17 );
      queue.print();
      queue.enqueue( 18 );
      queue.print();
      queue.enqueue( 19 );
      queue.print();
      queue.enqueue( 20 );
      queue.print();
      queue.enqueue( 21 );
      queue.print();
      queue.printDebugger();
      queue.enqueue( 31 );
      queue.printDebugger();
      queue.print();
      queue.makeEmpty();
      queue.print();

      System.out.println("Testing ArrayStack");
      ArrayStack stack = new ArrayStack();
      stack.printDebugger();
      stack.push(1);
      stack.printDebugger();
      removedObject = stack.pop();
      stack.printDebugger();
      removedObject = stack.pop();
      stack.printDebugger();
      stack.push(1);
      stack.printDebugger();
      stack.push(2);
      stack.push(3);
      stack.push(4);
      stack.push(5);
      stack.push(6);
      stack.push(7);
      stack.push(8);
      stack.push(9);
      stack.push(10);
      stack.printDebugger();
      removedObject = stack.pop();
      stack.printDebugger();
      removedObject = stack.pop();
      stack.printDebugger();
      removedObject = stack.pop();
      stack.printDebugger();
      removedObject = stack.pop();
      stack.printDebugger();
      removedObject = stack.pop();
      stack.printDebugger();
      removedObject = stack.pop();
      stack.printDebugger();
      removedObject = stack.pop();
      stack.printDebugger();
      removedObject = stack.pop();
      stack.printDebugger();
      removedObject = stack.pop();
      stack.printDebugger();
      removedObject = stack.pop();
      stack.printDebugger();
      removedObject = stack.pop();
      System.out.println("Removed "+removedObject);
      stack.printDebugger();
   } 
} 